// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Company struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Notes string `json:"notes"`
}

type CompanyType struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type CompanyTypeRel struct {
	ID            int64 `json:"id"`
	CompanyID     int64 `json:"company_id"`
	CompanyTypeID int64 `json:"company_type_id"`
}

type Contact struct {
	ID          int64  `json:"id"`
	CompanyID   int64  `json:"company_id"`
	JobPosition string `json:"job_position"`
	FistName    string `json:"fist_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	Notes       string `json:"notes"`
}

type Event struct {
	ID               int64  `json:"id"`
	SourceID         int64  `json:"source_id"`
	JobApplicationID int64  `json:"job_application_id"`
	Title            string `json:"title"`
	Date             int64  `json:"date"`
	Notes            string `json:"notes"`
}

type EventContact struct {
	ID        int64 `json:"id"`
	EventID   int64 `json:"event_id"`
	ContactID int64 `json:"contact_id"`
}

type EventSource struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type JobApplication struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	StatusID  int64  `json:"status_id"`
	JobTitle  string `json:"job_title"`
	Notes     string `json:"notes"`
}

type JobApplicationStatus struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
