// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCompany(arg1) {
  return window['go']['main']['App']['DeleteCompany'](arg1);
}

export function DeleteCompanyType(arg1) {
  return window['go']['main']['App']['DeleteCompanyType'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteEventSource(arg1) {
  return window['go']['main']['App']['DeleteEventSource'](arg1);
}

export function DeleteJobApplication(arg1) {
  return window['go']['main']['App']['DeleteJobApplication'](arg1);
}

export function DeleteJobApplicationStatus(arg1) {
  return window['go']['main']['App']['DeleteJobApplicationStatus'](arg1);
}

export function InsertCompany(arg1) {
  return window['go']['main']['App']['InsertCompany'](arg1);
}

export function InsertCompanyType(arg1) {
  return window['go']['main']['App']['InsertCompanyType'](arg1);
}

export function InsertContact(arg1) {
  return window['go']['main']['App']['InsertContact'](arg1);
}

export function InsertEvent(arg1) {
  return window['go']['main']['App']['InsertEvent'](arg1);
}

export function InsertEventSource(arg1) {
  return window['go']['main']['App']['InsertEventSource'](arg1);
}

export function InsertJobApplication(arg1) {
  return window['go']['main']['App']['InsertJobApplication'](arg1);
}

export function InsertJobApplicationStatus(arg1) {
  return window['go']['main']['App']['InsertJobApplicationStatus'](arg1);
}

export function ListCompanies() {
  return window['go']['main']['App']['ListCompanies']();
}

export function ListCompanyTypes() {
  return window['go']['main']['App']['ListCompanyTypes']();
}

export function ListContact() {
  return window['go']['main']['App']['ListContact']();
}

export function ListEventSource() {
  return window['go']['main']['App']['ListEventSource']();
}

export function ListEvents() {
  return window['go']['main']['App']['ListEvents']();
}

export function ListJobApplication() {
  return window['go']['main']['App']['ListJobApplication']();
}

export function ListJobApplicationStatus() {
  return window['go']['main']['App']['ListJobApplicationStatus']();
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateCompanyType(arg1) {
  return window['go']['main']['App']['UpdateCompanyType'](arg1);
}

export function UpdateContact(arg1) {
  return window['go']['main']['App']['UpdateContact'](arg1);
}

export function UpdateEvent(arg1) {
  return window['go']['main']['App']['UpdateEvent'](arg1);
}

export function UpdateEventSource(arg1) {
  return window['go']['main']['App']['UpdateEventSource'](arg1);
}

export function UpdateJobApplication(arg1) {
  return window['go']['main']['App']['UpdateJobApplication'](arg1);
}

export function UpdateJobApplicationStatus(arg1) {
  return window['go']['main']['App']['UpdateJobApplicationStatus'](arg1);
}
